travis:
  secure:
    BINSTAR_TOKEN: RtcItKNiUldgkKuuYa+lG/J1wT3PBk+VLtAGLJA6nrrwdm1iMFEto3XF5Eu8HglVTXs2mOFPRqpHiRB0sArogAlW0hBlY/8Z497S1D/m9U3OAPORfqfE6EjUmEM1qgQNcnSOwfSJPgrThR9pcJwHApCmlZtVanWudO3e/udzPL90mjhUfbjHaVqSfGr/aEhXlaHvBjxtwwC/QDjKB/7xxQfLcbUr9AGUMuAMlC1SHAMJxYtyRnJJh4VbJuypd7kz0yH8BcrRYuEyrMbURPnEZvtZszLcxXOPNdA+XTt4emK6Za+12y7OukvPQYksUZmbzGCj1kLoHrPc3Wfz2mGfK+pbfDVADL/ZlLrrWAbnhIk3bCREy8LpaJNc4otyrhZvx7DJrHm4NrenRXY7DgraRi/o2E85WJd7bHNKmth3C4+3djxn2fhMB70spUBZ5bE5Sx6RJ6VcU5dRn0nzOYATCaBsRL3O6DQrsB8bBGPAMbCrDQ6sB7HFS7PHMlMz0xT4whOc5yrGLOqMpmyI1IDkg4iYjX3n8SvfD8zbExUK8qKoHFKM6UrlZPzXkFotYAN0oezPzHkDGz3Q9LXlCLehdnGzHK/kEGtvMKjjt27fyl0wg9ZQHyFUYkIzixOvN1f3OybLhC6NG+K2EITft8C6YqJ+16TSRxp5HGotbgTy0Bw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
